sudo: false
language: c++

compiler:
  - gcc
  - clang
#before_cache:
cache:
  directories:
    - bin/Externals
#before_install:
install:
  # C++11 support required
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data
    - gcc-4.8
    - g++-4.8
    - clang
#before_script:
script:
  - cd bin
  - cmake -DBUILD_TESTING:BOOL=OFF -DBUILD_MOSAIC_TOOLS:BOOL=OFF ../Superbuild
  - make -j4
#after_failure:
#after_success:
#after_script:
